PYTHON = python

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  fetch         to fetch the data"
	@echo "  preproces      to run all scripts after anatomy. LFREQ must be set for highpass cutoff"
	@echo "  check         check if the dependencies are available"
	@echo "  profile       to profile memory consumption"
	@echo "  all           to build fetch data, run anatomy scripts and all the processing scripts with no highpass"
	@echo "  clean		remove intermediate scripts generated by processing"

check:
	$(PYTHON) check_system.py

clean:
	$(PYTHON) clean.py

fetch:
	$(PYTHON) 00-fetch_data.py

preproces:
	$(PYTHON) 01-frequency_filtering.py
	$(PYTHON) 02-maxwell_filtering.py
	$(PYTHON) 03-extract_events.py
	$(PYTHON) 04-artifact_correction_ica.py
	$(PYTHON) 04-artifact_correction_ssp.py
	$(PYTHON) 05-make_epochs.py
	$(PYTHON) 06-make_evoked.py
    $(PYTHON) 08-make_cov.py

time-frequency:
    $(PYTHON) 09-time_frequency.py

source-space:
    $(PYTHON) 01-anatomy.py
    $(PYTHON) 10-sliding_estimator.py
    $(PYTHON) 11-group_average_sensors.py
    $(PYTHON) 12-make_forward.py
    $(PYTHON) 13-make_inverse.py
    $(PYTHON) 14-group_average_source.py
    $(PYTHON) 15-lcmv_beamformer.py
    $(PYTHON) 16-group_average_lcmv.py

all:
	$(MAKE) fetch
	$(MAKE) preproces
