version: 2
jobs:
    build_docs:
      docker:
        # 3.6-jessie is too new for conda
        - image: circleci/python:3.6-jessie
      steps:
        - checkout
        - run:
            name: Set BASH_ENV
            command: |
              echo "set -e" >> $BASH_ENV;
              echo "export SUBJECTS_DIR=~/mne_data/MNE-sample-data/subjects" >> $BASH_ENV;
              echo "export DISPLAY=:99" >> $BASH_ENV;
              echo "export OPENBLAS_NUM_THREADS=4" >> $BASH_ENV;
              echo "export PATH=~/miniconda/bin:$PATH" >> $BASH_ENV;

        # Load our data
        - restore_cache:
            keys:
              - data-cache-0
              - pip-cache

        - run:
            name: Spin up Xvfb
            command: |
              /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;

        # https://github.com/ContinuumIO/anaconda-issues/issues/9190#issuecomment-386508136
        # https://github.com/golemfactory/golem/issues/1019
        - run:
            name: Fix libgcc_s.so.1 pthread_cancel bug
            command: |
              sudo apt-get install libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 qt5-default

        - run:
            name: Get Anaconda running
            command: |
              wget -q http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh;
              chmod +x ~/miniconda.sh;
              ~/miniconda.sh -b -p ~/miniconda;
              export export PATH=~/miniconda/bin:$PATH;
              conda update --yes --quiet conda;
              curl -O https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
              conda env create -f environment.yml
              source activate mne
              echo "source activate mne" >> $BASH_ENV;

        - save_cache:
            key: pip-cache
            paths:
              - ~/.cache/pip

        # Look at what we have and fail early if there is some library conflict
        - run:
            name: Check installation
            command: |
               which python
               python -c "import mne; mne.sys_info()"

        - run:
            name: Get data
            command: |
              mkdir -p ~/mne_data
              make fetch

        - run:
            name: Verify data is there
            command: |
              ls -al ~/mne_data;

        # Run the scripts
        - run:
            name: make html
            command: |
              make preproces

        - run:
            name: make html
            command: |
              make time-frequency

        - run:
            name: make html
            command: |
              make source-space

        # Save the outputs
        - store_artifacts:
            path: doc/_build/html/
            destination: dev
        - store_artifacts:
            path: doc/_build/html_stable/
            destination: stable

        # Store the cache
        - save_cache:
            key: data-cache-0
            paths:
              - ~/mne_data/MNE-sample-data


workflows:
  version: 2

  default:
    jobs:
      - build_docs
